homeassistant:
  # Name of the location where Home Assistant is running
  name: Mihanich's Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.6289626
  longitude: 22.27226181
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 115
  # metric for Metric, imperial for Imperial
  temperature_unit: C
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  api_password: 12345678

api:
#websocket_api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# DarkSky weather
weather:
  - platform: darksky
    api_key: 4216a52dfd10cd3b72549c4e9a743f9e
    mode: daily
    
# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

light:
  - platform: yeelight
    devices:
      192.168.2.217:
        name: desktop lamp
        model: lamp1

# Xiaomi .
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: F0B429CFB749
      host: 192.168.2.95
      key: ex8w2sw0z029zse7

media_player:
  - platform: squeezebox
    host: localhost
    username: mihanich
    password: M1xan1ch

mqtt:
  broker: localhost
  username: homeassistant
  password: H0me12345

climate:
  - platform: mqtt

    # Change to whatever you want
    name: livingroom AC

    # Change MQTT_TOPIC_PREFIX to what you've set in addon options
    current_temperature_topic: "home/greehvac/temperature/get"
    temperature_command_topic: "home/greehvac/temperature/set"
    temperature_state_topic: "home/greehvac/temperature/get"
    mode_state_topic: "home/greehvac/mode/get"
    mode_command_topic: "home/greehvac/mode/set"
    fan_mode_state_topic: "home/greehvac/fanspeed/get"
    fan_mode_command_topic: "home/greehvac/fanspeed/set"
    swing_mode_state_topic: "home/greehvac/swingvert/get"
    swing_mode_command_topic: "home/greehvac/swingvert/set"
    power_state_topic: "home/greehvac/power/get"
    power_command_topic: "home/greehvac/power/set"

    # Keep the following as is
    payload_off: 0
    payload_on: 1
    modes:
      - "off"
      - "auto"
      - "cool"
      - "heat"
      - "dry"
      - "fan_only"
    swing_modes:
      - "default"
      - "full"
      - "fixedTop"
      - "fixedMidTop"
      - "fixedMid"
      - "fixedMidBottom"
      - "fixedBottom"
      - "swingBottom"
      - "swingMidBottom"
      - "swingMid"
      - "swingMidTop"
      - "swingTop"
    fan_modes:
      - "auto"
      - "low"
      - "mediumLow"
      - "medium"
      - "mediumHigh"
      - "high"

#logger:
#  default: error
#  logs:
#    custom_components.climate.gree: info

# device tracking
#device_tracker:
#  - platform: bluetooth_tracker

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
